name: CI

on: ['push']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 1
      - name: Set up Python
        uses: actions/setup-python@v4.3.0
        with: 
          python-version: 3.9
      - name: Install Poetry
        uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.2.2
      - name: Cache Poetry virtualenv
        id: cache
        uses: actions/cache@v3.0.11
        with:
          path: ~/.virtualenvs
          key: poetry-${{hashFiles('**poetry.lock')}}
          restore-keys: poetry-${{hashFiles('**poetry.lock')}}
      - name: Set Poetry config
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~./virtualenvs
      - name: Install Dependencies
        run: poetry install --no-interaction --no-root
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Install project
        run: poetry install --no-interaction
      - name: Run Tests
        run: poetry run -m unittest